language: go

go:
  - 1.9

before_install:
  - go get -t -v ./...
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)